ruby '2.6.2'
source "https://rubygems.org"

gem 'rubocop'
gem 'ruby-debug-ide'
gem 'debase'
gem 'rcodetools'
gem 'fastri'

gem 'sinatra'
gem 'sinatra-contrib'

gem 'activerecord', '~> 6.1'
gem 'sinatra-activerecord', '~> 2.0'
gem 'pg', '~> 1.2'
gem 'rake', '~> 13.0'
gem 'bcrypt'
